import React from 'react'

import Head from 'next/head'
//This component is for SEO optimization
const HeadComponent = ({title,  metaDescription}) => {
  return (
    <Head>
      <title>{title ? title : 'Agencia de ecommerce'}</title>
      <meta
        name="description"
        content="Generated by create next app"
      />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}

export default HeadComponent